stages:
  - build
  - unit-test
  - widget-test
  - integration-test
  - golden-test

variables:
  FLUTTER_VERSION: '3.x'
  JAVA_VERSION: '12'

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - curl -sL https://github.com/flutter/flutter/archive/refs/tags/$FLUTTER_VERSION.tar.gz | tar -xz
  - export PATH="$PATH:$PWD/flutter-$FLUTTER_VERSION/bin"
  - flutter doctor
  - flutter --version

build:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get install -y openjdk-$JAVA_VERSION-jdk
    - flutter pub get
    - flutter analyze
    - flutter test

unit-test:
  stage: unit-test
  image: ubuntu:latest
  script:
    - apt-get install -y openjdk-$JAVA_VERSION-jdk
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/unit_test

widget-test:
  stage: widget-test
  image: ubuntu:latest
  script:
    - apt-get install -y openjdk-$JAVA_VERSION-jdk
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/widget_test

integration-test:
  stage: integration-test
  image: ubuntu:latest
  script:
    - apt-get install -y openjdk-$JAVA_VERSION-jdk
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/integration_test

golden-test:
  stage: golden-test
  image: ubuntu:latest
  script:
    - apt-get install -y openjdk-$JAVA_VERSION-jdk
    - flutter pub get
    - flutter analyze
    - flutter test --coverage --update-goldens test/golden_test

