image: khoironrois/linux-ubuntu-flutter:latest

stages:
#  - build
  - unit-test
  - widget-test
  - integration-test
  - golden-test

variables:
  FLUTTER_VERSION: '3.22.1-stable'
  JAVA_VERSION: '11'

before_script:
#  - flutter channel stable
#  - flutter upgrade
  - flutter doctor --version
#  - flutter --version

build:
  stage: build
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test

unit-test:
  stage: unit-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/unit_test

widget-test:
  stage: widget-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/widget_test

integration-test:
  stage: integration-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/integration_test

golden-test:
  stage: golden-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage --update-goldens test/golden_test
