image: growerp/flutter-sdk-image:latest

stages:
  - build
  - unit_test
  - widget_test
  - integration_test
  - golden_test

variables:
  JAVA_VERSION: "12"

before_script:
  #  - flutter channel stable
  #  - flutter upgrade
  - flutter pub get

build:
  stage: build
  script:
    - flutter --version
    - flutter analyze

unit-test:
  stage: unit_test
  script:
    - cd test/unit_test
    - flutter test --coverage

widget-test:
  stage: widget_test
  script:
    - cd test/widget_test
    - flutter test --coverage

integration-test:
  stage: integration_test
  script:
    - cd test
    - flutter test --coverage integration_test

golden_test:
  stage: golden_test
  script:
    - flutter test --coverage --update-goldens test/golden_test