image: ubuntu:latest

stages:
  - setup
  - build
  - test
  - unit_test
  - widget_test
  - integration_test
  - golden_test

variables:
  JAVA_VERSION: "12"

before_script:
  - apt-get update -qy
  - apt-get install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wget
  - wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_2.8.1-stable.tar.xz
  - tar xf flutter_linux_2.8.1-stable.tar.xz -C /usr
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor
  - flutter pub get

setup:
  stage: setup
  script:
    - apt-get install -y build-essential libsqlite3-dev

build:
  stage: build
  script:
    - flutter --version
    - flutter analyze

test:
  stage: test
  before_script:
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage test/unit_test
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage

unit-test:
  stage: unit_test
  script:
    - flutter test test/unit_test --coverage

widget-test:
  stage: widget_test
  script:
    - flutter test test/widget_test --coverage

integration-test:
  stage: integration_test
  script:
    - flutter test test/integration_test --coverage

golden_test:
  stage: golden_test
  script:
    - flutter test  --update-goldens test/golden_test --coverage