image: growerp/flutter-sdk-image:latest

stages:
  - build
  - test
  - unit_test
  - widget_test
  - integration_test
  - golden_test

variables:
  JAVA_VERSION: "12"

before_script:
  #  - flutter channel stable
  #  - flutter upgrade
  - flutter pub get

build:
  stage: build
  script:
    - flutter --version
    - flutter analyze

test:
  stage: test
  image: debian:stable-slim
  before_script:
    - apt-get update -qy
    - apt-get install -y build-essential libsqlite3-dev
    - flutter pub global activate junitreport
    - export PATH="$PATH:$HOME/.pub-cache/bin"
  script:
    - flutter test --machine --coverage test/unit_test
    - lcov --summary coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage
  coverage: '/lines\.*: \d+\.\d+\%/'
  artifacts:
    name: coverage
    paths:
      - $CI_PROJECT_DIR/coverage
#    reports:
#      junit: coverage/report.xml


unit-test:
  stage: unit_test
  script:
    - flutter test test/unit_test --coverage

widget-test:
  stage: widget_test
  script:
    - flutter test test/widget_test --coverage

integration-test:
  stage: integration_test
  script:
    - flutter test test/integration_test --coverage

golden_test:
  stage: golden_test
  script:
    - flutter test  --update-goldens test/golden_test --coverage