image: scm.getih.net:5050/dsi-container-images/docker-flutter/flutter-dsi:latest

stages:
  - build
  - test

variables:
  JAVA_VERSION: "12"

before_script:
#  - flutter channel stable
#  - flutter upgrade
  - flutter pub get

build:
  stage: build
  script:
    - flutter --version
    - flutter analyze

test:
  stage: test
  script:
    - flutter test