stages:
  - build
  - unit-test
  - widget-test
  - integration-test
  - golden-test

variables:
  FLUTTER_VERSION: '3.22.0-stable'
  JAVA_VERSION: '12.x'

before_script:
  - apt-get update && apt-get install -y curl unzip
  - curl -sL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  - apt-get install -y openjdk-$JAVA_VERSION
  - curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_$FLUTTER_VERSION.tar.xz | tar -xJ
  - export PATH="$PATH:$PWD/flutter/bin"
  - flutter doctor
  - flutter --version

build:
  stage: build
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test

unit-test:
  stage: unit-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/unit_test

widget-test:
  stage: widget-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/widget_test

integration-test:
  stage: integration-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/integration_test

golden-test:
  stage: golden-test
  image: ubuntu:latest
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage --update-goldens test/golden_test
